version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"  # Porta externa:interna
    environment:
      - NODE_ENV=production
    # command já está definido no Dockerfile, então não é obrigatório aqui

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
